/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import MainWindow.*;
/**
 *
 * @author skasr
 */
public class LoginMain extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    /**
     * Creates new form LoginMain
     */
    MainWindow mw;
    public LoginMain(MainWindow mw) {
        initComponents();
        this.setLocationRelativeTo(null);
        MainPanel.setFocusable(true);
        this.mw = mw;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        txfield_usrnm = new javax.swing.JTextField();
        pswfield_psw = new javax.swing.JPasswordField();
        but_logo = new javax.swing.JLabel();
        gotoregister = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MainPanelKeyPressed(evt);
            }
        });
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfield_usrnm.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txfield_usrnm.setForeground(new java.awt.Color(102, 102, 102));
        txfield_usrnm.setText("Enter user name");
        txfield_usrnm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txfield_usrnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfield_usrnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfield_usrnmFocusLost(evt);
            }
        });
        txfield_usrnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfield_usrnmActionPerformed(evt);
            }
        });
        txfield_usrnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfield_usrnmKeyPressed(evt);
            }
        });
        MainPanel.add(txfield_usrnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 160, 30));

        pswfield_psw.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        pswfield_psw.setForeground(new java.awt.Color(102, 102, 102));
        pswfield_psw.setText("Enter password");
        pswfield_psw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pswfield_psw.setEchoChar('\u0000');
        pswfield_psw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswfield_pswFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswfield_pswFocusLost(evt);
            }
        });
        pswfield_psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswfield_pswActionPerformed(evt);
            }
        });
        pswfield_psw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswfield_pswKeyPressed(evt);
            }
        });
        MainPanel.add(pswfield_psw, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 160, 40));

        but_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiny-butterfly-logo.png"))); // NOI18N
        MainPanel.add(but_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 80, 70));

        gotoregister.setForeground(new java.awt.Color(0, 102, 102));
        gotoregister.setText("First time? Register.");
        gotoregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoregisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotoregisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gotoregisterMousePressed(evt);
            }
        });
        MainPanel.add(gotoregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfield_usrnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfield_usrnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfield_usrnmActionPerformed

    private void pswfield_pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswfield_pswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswfield_pswActionPerformed

    private void txfield_usrnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfield_usrnmFocusGained
        // TODO add your handling code here:
        if(txfield_usrnm.getText().trim().equals("Enter user name"))
        {
            txfield_usrnm.setText("");
        }
        
        txfield_usrnm.setForeground(Color.BLACK);
    }//GEN-LAST:event_txfield_usrnmFocusGained

    private void pswfield_pswFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfield_pswFocusGained
        // TODO add your handling code here:
        if(pswfield_psw.getText().trim().equals("Enter password"))
        {
            pswfield_psw.setText("");
        }
        
        pswfield_psw.setForeground(Color.BLACK);
        pswfield_psw.setEchoChar('*');
    }//GEN-LAST:event_pswfield_pswFocusGained

    private void txfield_usrnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfield_usrnmFocusLost
        // TODO add your handling code here:
         if(txfield_usrnm.getText().trim().equals(""))
        {
            txfield_usrnm.setText("Enter user name");
            txfield_usrnm.setForeground(new Color(102,102,102));
        }
        
        
    }//GEN-LAST:event_txfield_usrnmFocusLost

    private void pswfield_pswFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfield_pswFocusLost
        // TODO add your handling code here:
        if(pswfield_psw.getText().trim().equals(""))
        {
            pswfield_psw.setText("Enter password");
             pswfield_psw.setForeground(new Color(102,102,102));
            pswfield_psw.setEchoChar('\u0000');
        }
        
       
    }//GEN-LAST:event_pswfield_pswFocusLost

    private void MainPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MainPanelKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
           
       
        String username = txfield_usrnm.getText();
        
        conn = MySqlConnect.ConnectDB();
        String Sql="Select * from login where username=? and password=?";
        try {
            pst=conn.prepareStatement(Sql);
            pst.setString(1, username);
            pst.setString(2, pswfield_psw.getText());
            
            rs = pst.executeQuery();
            if(rs.next()) {
                mw.setwelcome(username);
                mw.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid username or password","Access Denied",JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginMain.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_MainPanelKeyPressed

    private void txfield_usrnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfield_usrnmKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            MainPanelKeyPressed(evt);
        }
    }//GEN-LAST:event_txfield_usrnmKeyPressed

    private void pswfield_pswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswfield_pswKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            MainPanelKeyPressed(evt);
        }
    }//GEN-LAST:event_pswfield_pswKeyPressed

    private void gotoregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMouseEntered
        // TODO add your handling code here:
        gotoregister.setForeground(Color.BLACK);
    }//GEN-LAST:event_gotoregisterMouseEntered

    private void gotoregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMouseExited
        // TODO add your handling code here:
        gotoregister.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_gotoregisterMouseExited

    private void gotoregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_gotoregisterMouseClicked

    private void gotoregisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMousePressed
        // TODO add your handling code here:
        JFrame jf = new RegisterForm();
        
        jf.setVisible(true);
    }//GEN-LAST:event_gotoregisterMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginMain().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel but_logo;
    private javax.swing.JLabel gotoregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pswfield_psw;
    private javax.swing.JTextField txfield_usrnm;
    // End of variables declaration//GEN-END:variables
}
