/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author skasr
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(null);
        jButton1.setBackground(Color.WHITE);
        jPanel1.setFocusable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfield_usrnm = new javax.swing.JTextField();
        pswfield_psw = new javax.swing.JPasswordField();
        pswfield_repsw = new javax.swing.JPasswordField();
        label_err = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        gotoregister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 30));

        txfield_usrnm.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txfield_usrnm.setForeground(new java.awt.Color(102, 102, 102));
        txfield_usrnm.setText("Enter user name");
        txfield_usrnm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txfield_usrnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfield_usrnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfield_usrnmFocusLost(evt);
            }
        });
        txfield_usrnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfield_usrnmActionPerformed(evt);
            }
        });
        txfield_usrnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfield_usrnmKeyPressed(evt);
            }
        });
        jPanel1.add(txfield_usrnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 160, 30));

        pswfield_psw.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        pswfield_psw.setForeground(new java.awt.Color(102, 102, 102));
        pswfield_psw.setText("Enter password");
        pswfield_psw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pswfield_psw.setEchoChar('\u0000');
        pswfield_psw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswfield_pswFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswfield_pswFocusLost(evt);
            }
        });
        pswfield_psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswfield_pswActionPerformed(evt);
            }
        });
        pswfield_psw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswfield_pswKeyPressed(evt);
            }
        });
        jPanel1.add(pswfield_psw, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 160, 40));

        pswfield_repsw.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        pswfield_repsw.setForeground(new java.awt.Color(102, 102, 102));
        pswfield_repsw.setText("Enter password again");
        pswfield_repsw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pswfield_repsw.setEchoChar('\u0000');
        pswfield_repsw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswfield_repswFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswfield_repswFocusLost(evt);
            }
        });
        pswfield_repsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswfield_repswActionPerformed(evt);
            }
        });
        pswfield_repsw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswfield_repswKeyPressed(evt);
            }
        });
        jPanel1.add(pswfield_repsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 160, 40));

        label_err.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(label_err, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 160, 20));

        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 110, 40));

        gotoregister.setForeground(new java.awt.Color(0, 102, 102));
        gotoregister.setText("Go back to login");
        gotoregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoregisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotoregisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gotoregisterMousePressed(evt);
            }
        });
        jPanel1.add(gotoregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfield_usrnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfield_usrnmFocusGained
        // TODO add your handling code here:
        label_err.setText("");
        if(txfield_usrnm.getText().trim().equals("Enter user name"))
        {
            txfield_usrnm.setText("");
        }

        txfield_usrnm.setForeground(Color.BLACK);
    }//GEN-LAST:event_txfield_usrnmFocusGained

    private void txfield_usrnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfield_usrnmFocusLost
        // TODO add your handling code here:
        if(txfield_usrnm.getText().trim().equals(""))
        {
            txfield_usrnm.setText("Enter user name");
            txfield_usrnm.setForeground(new Color(102,102,102));
        }

    }//GEN-LAST:event_txfield_usrnmFocusLost

    private void txfield_usrnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfield_usrnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfield_usrnmActionPerformed

    private void txfield_usrnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfield_usrnmKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txfield_usrnmKeyPressed

    private void pswfield_pswFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfield_pswFocusGained
        // TODO add your handling code here:
        label_err.setText("");
        if(pswfield_psw.getText().trim().equals("Enter password"))
        {
            pswfield_psw.setText("");
        }

        pswfield_psw.setForeground(Color.BLACK);
        pswfield_psw.setEchoChar('*');
    }//GEN-LAST:event_pswfield_pswFocusGained

    private void pswfield_pswFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfield_pswFocusLost
        // TODO add your handling code here:
        if(pswfield_psw.getText().trim().equals(""))
        {
            pswfield_psw.setText("Enter password");
            pswfield_psw.setForeground(new Color(102,102,102));
            pswfield_psw.setEchoChar('\u0000');
        }

    }//GEN-LAST:event_pswfield_pswFocusLost

    private void pswfield_pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswfield_pswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswfield_pswActionPerformed

    private void pswfield_pswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswfield_pswKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pswfield_pswKeyPressed

    private void pswfield_repswFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfield_repswFocusGained
        // TODO add your handling code here:
        label_err.setText("");
        if(pswfield_repsw.getText().trim().equals("Enter password again"))
        {
            pswfield_repsw.setText("");
        }

        pswfield_repsw.setForeground(Color.BLACK);
        pswfield_repsw.setEchoChar('*');
    }//GEN-LAST:event_pswfield_repswFocusGained

    private void pswfield_repswFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfield_repswFocusLost
        // TODO add your handling code here:
        if(pswfield_repsw.getText().trim().equals(""))
        {
            pswfield_repsw.setText("Enter password again");
            pswfield_repsw.setForeground(new Color(102,102,102));
            pswfield_repsw.setEchoChar('\u0000');
        }

    }//GEN-LAST:event_pswfield_repswFocusLost

    private void pswfield_repswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswfield_repswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswfield_repswActionPerformed

    private void pswfield_repswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswfield_repswKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pswfield_repswKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String uname = txfield_usrnm.getText();
        String password = String.valueOf(pswfield_psw.getPassword());
        String repassword = String.valueOf(pswfield_repsw.getPassword());
        if(!(password.equals(repassword)))
        {
            label_err.setText("The passwords don't match.");
            return;
        }
        PreparedStatement ps;
        String query = "INSERT INTO login values(?,?)";
        try {
            ps = MySqlConnect.ConnectDB().prepareStatement(query);
            ps.setString(1, uname);
            ps.setString(2, password);
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Successfully registered");
                this.dispose();
            }
        } catch (SQLException ex) {
             label_err.setText("User already exists");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setForeground(Color.WHITE);
        jButton1.setBackground(Color.BLACK);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setForeground(Color.BLACK);
        jButton1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton1MouseExited

    private void gotoregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_gotoregisterMouseClicked

    private void gotoregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMouseEntered
        // TODO add your handling code here:
        gotoregister.setForeground(Color.BLACK);
    }//GEN-LAST:event_gotoregisterMouseEntered

    private void gotoregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMouseExited
        // TODO add your handling code here:
        gotoregister.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_gotoregisterMouseExited

    private void gotoregisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoregisterMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_gotoregisterMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gotoregister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_err;
    private javax.swing.JPasswordField pswfield_psw;
    private javax.swing.JPasswordField pswfield_repsw;
    private javax.swing.JTextField txfield_usrnm;
    // End of variables declaration//GEN-END:variables
}
